[project]
name = "freshapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ctkmessagebox>=2.7",
    "customtkinter>=5.2.2",
    "dotenv>=0.9.9",
    "pillow>=11.3.0",
    "requests>=2.32.4",
    "tomli>=2.2.1",
]
